### ISSUE TITLE
Bridgebeam tweaks in production

### ISSUE THREAD

**Issue by elioqoshi** [uradotdesign/bridgebeam#1]
I provided feedback via Pastel for @AnXh3L0  here:
https://usepastel.com/link/ony9nq03/

**Comment by elioqoshi** [comment]
@AnXh3L0 it would be good if you can make the repo public as well (not MIT licensing ideally) and provide some documentation in the readme how the page is built

**Comment by AnXh3L0** [comment]
I have implemented the feedback from the usepastel link and also set a GPL license for the repo. Additionally, I edited the README to provide docs on how the page is built.
