### ISSUE TITLE
Bridgebeam German translation & other tweaks

### ISSUE THREAD

**Issue by elioqoshi** [uradotdesign/bridgebeam#3]
We have German translations updated:
https://www.figma.com/file/3O81PWEsx8kqQr3EPwZ6Io/Bridgebeam-Website?type=design&node-id=336%3A12049&mode=design&t=qSdnvcqsvl2yeAPm-1

Included also some changes in the designs which I tagged you on @AnXh3L0

**Comment by AnXh3L0** [comment]
Applied the German translations, new designs and deployed on production as well.
